In [5]:
import duckdb as dd

In [6]:
dd.sql("SElECT * FROM 'page_groups_CPMVertex_01_finalized.parquet' AS mytable ORDER BY mytable.group").df()

                             title   group
0                        Akashlina       0
1                            Partu       0
2                             Soni       0
3                         Bhardaha       0
4                      Soni_(name)       0
...                            ...     ...
3346763             Urspelt_Castle  483718
3346764    Partitioning_of_Prussia  483719
3346765  Cody_Johnson_(footballer)  483720
3346766            Joel_D._Hubbard  483721
3346767                 Robin_Witt  483722

[3346768 rows x 2 columns]

In [7]:
dd.sql("SElECT * FROM 'page_groups_CPMVertex_04_finalized.parquet' AS mytable ORDER BY mytable.group").df()

                                             title   group
0                                         Nerverek       0
1        30th_International_Film_Festival_of_India       0
2                     Nungambakkam_railway_station       0
3                              Project_Malabaricus       0
4                            Histidine—tRNA_ligase       0
...                                            ...     ...
3346763                             Chandana_Dixit  582937
3346764                                     Finder  582938
3346765               Steven_Blum_(disambiguation)  582939
3346766                                 Dear_Death  582940
3346767                             Bishwo_Airways  582941

[3346768 rows x 2 columns]